services:
  - type: web
    name: whatsapp-gpt-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        value: tu_clave_de_openai